d = {}

name = input("ENter your name :")
lang = input("Enter Language name :")
d.update({name : lang})
name = input("ENter your name :")
lang = input("Enter Language name :")
d.update({name : lang})
name = input("ENter your name :")
lang = input("Enter Language name :")
d.update({name : lang})
name = input("ENter your name :")
lang = input("Enter Language name :")
d.update({name : lang})
print(d)